# Generated by Django 4.1.1 on 2022-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
